package cli

import (
	"fmt"
	"testing"
	"time"

	"github.com/jack-work/figaro/internal/livedoc"
	"github.com/jack-work/figaro/internal/livelog/aria"
	ldrender "github.com/jack-work/figaro/internal/livelog/render"
)

// ---------------------------------------------------------------------------
// Behavioural equivalence: the keymap must do exactly what the five inline
// switches did.
//
// The table below was GENERATED by running the pre-refactor code (45bee38,
// "docs(cli): the help panel and ui-stream list the arrow cluster") over every
// key in every pager mode and recording the resulting state. It is a frozen
// oracle, not an aspiration: the refactor is correct exactly insofar as it
// reproduces this, and any future change to a binding has to change a line
// here on purpose.
//
// Each row is a starting state: the signature an INERT key leaves (an unbound
// control byte), plus every key that leaves something else. So a key missing
// from the map is an assertion too — it must be a no-op in that mode.
// ---------------------------------------------------------------------------

// oracleTranscript is the fixture the oracle was recorded against: eight
// two-node messages in a 50x8 pane, entered (and so following the tail).
func oracleTranscript() *transcript {
	ft := ldrender.NewFakeTerminal(50, 8)
	client := aria.NewClient()
	for i := 1; i <= 8; i++ {
		client.Apply(aria.Page{Parts: []aria.TurnPart{{Turn: aria.Turn{
			ID: uint64(i), Sealed: true,
			Nodes: []livedoc.Node{
				{Type: livedoc.NodeProse, Markdown: fmt.Sprintf("msg%02d body", i)},
				{Type: livedoc.NodeTool, Name: "bash", Output: fmt.Sprintf("out%02d", i)},
			},
		}}}})
	}
	tr := newTranscript(ft, 50, 8, ldrender.NodeText{}, client, "aria1234", time.Unix(0, 0))
	tr.enter()
	return tr
}

// oracleSignature is every piece of pager state a keystroke can touch.
func oracleSignature(tr *transcript) string {
	return fmt.Sprintf("off=%d fol=%v srch=%v q=%q mq=%q h=%v s=%v Q=%v g=%v sel=%v old=%v new=%v exp=%d",
		tr.offset, tr.follow, tr.inSearch, tr.query, tr.matchQuery,
		tr.showHelp, tr.showStatus, tr.showQueued, tr.pendG, tr.selection.active,
		tr.checkOlder, tr.checkNewer, len(tr.expanded))
}

// The starting states, by the name the oracle records them under.
var oracleStates = map[string]func(*transcript){
	"transcript":       func(tr *transcript) {},
	"transcript+sel":   func(tr *transcript) { tr.selectNode(1, false); tr.render() },
	"transcript+pendG": func(tr *transcript) { tr.key('g') },
	"help":             func(tr *transcript) { tr.key('?') },
	"status":           func(tr *transcript) { tr.key('!') },
	"queued":           func(tr *transcript) { tr.key('Q') },
	"panel+sel":        func(tr *transcript) { tr.selectNode(1, false); tr.key('!') },
	"search":           func(tr *transcript) { tr.key('/'); tr.key('m'); tr.key('s') },
	"search+sel":       func(tr *transcript) { tr.selectNode(1, false); tr.key('/'); tr.key('m') },
}

var pagerOracle = []struct {
	state string
	inert string
	keys  map[string]string
}{
	{"transcript", "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0", map[string]string{
		"0x0e": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x10": "off=71 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x21": "off=76 fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false old=false new=false exp=0",
		"0x2f": "off=72 fol=true srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x3f": "off=76 fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x51": "off=75 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false old=false new=false exp=0",
		"0x64": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x67": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=true sel=false old=false new=false exp=0",
		"0x6a": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x6b": "off=70 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"0x75": "off=67 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"Down": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"Home": "off=0 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"PgDn": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"PgUp": "off=67 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"Up":   "off=70 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
	}},
	{"transcript+sel", "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0", map[string]string{
		"0x10": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=true new=false exp=0",
		"0x1b": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x21": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true old=false new=false exp=0",
		"0x2f": "off=2 fol=false srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x3f": "off=2 fol=false srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x47": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x51": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=true old=false new=false exp=0",
		"0x64": "off=6 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=true exp=0",
		"0x67": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=true sel=true old=false new=false exp=0",
		"0x6a": "off=3 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=true exp=0",
		"0x6b": "off=1 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=true new=false exp=0",
		"0x75": "off=0 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=true new=false exp=0",
		"Down": "off=3 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=true exp=0",
		"End":  "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"Home": "off=0 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=true new=false exp=0",
		"PgDn": "off=6 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=true exp=0",
		"PgUp": "off=0 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=true new=false exp=0",
		"Up":   "off=1 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=true new=false exp=0",
	}},
	{"transcript+pendG", "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0", map[string]string{
		"0x0e": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x10": "off=71 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x21": "off=76 fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false old=false new=false exp=0",
		"0x2f": "off=72 fol=true srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x3f": "off=76 fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x51": "off=75 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false old=false new=false exp=0",
		"0x64": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x67": "off=0 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"0x6a": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x6b": "off=70 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"0x75": "off=67 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"Down": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"Home": "off=0 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"PgDn": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"PgUp": "off=67 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"Up":   "off=70 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
	}},
	{"help", "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0", map[string]string{
		"0x0e": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x10": "off=71 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x21": "off=76 fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false old=false new=false exp=0",
		"0x2f": "off=72 fol=true srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x51": "off=75 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false old=false new=false exp=0",
		"0x64": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x67": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=true sel=false old=false new=false exp=0",
		"0x6a": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x6b": "off=70 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"0x75": "off=67 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"Down": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"Home": "off=0 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"PgDn": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"PgUp": "off=67 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"Up":   "off=70 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
	}},
	{"status", "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0", map[string]string{
		"0x0e": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x10": "off=71 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x2f": "off=72 fol=true srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x3f": "off=76 fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x51": "off=75 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false old=false new=false exp=0",
		"0x64": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x67": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=true sel=false old=false new=false exp=0",
		"0x6a": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x6b": "off=70 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"0x75": "off=67 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"Down": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"Home": "off=0 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"PgDn": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"PgUp": "off=67 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"Up":   "off=70 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
	}},
	{"queued", "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0", map[string]string{
		"0x0e": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x10": "off=71 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x21": "off=76 fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false old=false new=false exp=0",
		"0x2f": "off=72 fol=true srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x3f": "off=76 fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x64": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x67": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=true sel=false old=false new=false exp=0",
		"0x6a": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x6b": "off=70 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"0x75": "off=67 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"Down": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"Home": "off=0 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"PgDn": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"PgUp": "off=67 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
		"Up":   "off=70 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=true new=false exp=0",
	}},
	{"panel+sel", "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0", map[string]string{
		"0x10": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=true new=false exp=0",
		"0x2f": "off=2 fol=false srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x3f": "off=2 fol=false srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x47": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x51": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=true old=false new=false exp=0",
		"0x64": "off=6 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=true exp=0",
		"0x67": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=true sel=true old=false new=false exp=0",
		"0x6a": "off=3 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=true exp=0",
		"0x6b": "off=1 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=true new=false exp=0",
		"0x75": "off=0 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=true new=false exp=0",
		"Down": "off=3 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=true exp=0",
		"End":  "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"Home": "off=0 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=true new=false exp=0",
		"PgDn": "off=6 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=true exp=0",
		"PgUp": "off=0 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=true new=false exp=0",
		"Up":   "off=1 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=true new=false exp=0",
	}},
	{"search", "off=72 fol=true srch=true q=\"ms\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0", map[string]string{
		"0x08": "off=72 fol=true srch=true q=\"m\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x0a": "off=71 fol=false srch=false q=\"ms\" mq=\"ms\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x0d": "off=71 fol=false srch=false q=\"ms\" mq=\"ms\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x1b": "off=72 fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x20": "off=72 fol=true srch=true q=\"ms \" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x21": "off=72 fol=true srch=true q=\"ms!\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x22": "off=72 fol=true srch=true q=\"ms\\\"\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x23": "off=72 fol=true srch=true q=\"ms#\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x24": "off=72 fol=true srch=true q=\"ms$\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x25": "off=72 fol=true srch=true q=\"ms%\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x26": "off=72 fol=true srch=true q=\"ms&\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x27": "off=72 fol=true srch=true q=\"ms'\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x28": "off=72 fol=true srch=true q=\"ms(\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x29": "off=72 fol=true srch=true q=\"ms)\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x2a": "off=72 fol=true srch=true q=\"ms*\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x2b": "off=72 fol=true srch=true q=\"ms+\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x2c": "off=72 fol=true srch=true q=\"ms,\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x2d": "off=72 fol=true srch=true q=\"ms-\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x2e": "off=72 fol=true srch=true q=\"ms.\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x2f": "off=72 fol=true srch=true q=\"ms/\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x30": "off=72 fol=true srch=true q=\"ms0\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x31": "off=72 fol=true srch=true q=\"ms1\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x32": "off=72 fol=true srch=true q=\"ms2\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x33": "off=72 fol=true srch=true q=\"ms3\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x34": "off=72 fol=true srch=true q=\"ms4\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x35": "off=72 fol=true srch=true q=\"ms5\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x36": "off=72 fol=true srch=true q=\"ms6\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x37": "off=72 fol=true srch=true q=\"ms7\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x38": "off=72 fol=true srch=true q=\"ms8\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x39": "off=72 fol=true srch=true q=\"ms9\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x3a": "off=72 fol=true srch=true q=\"ms:\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x3b": "off=72 fol=true srch=true q=\"ms;\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x3c": "off=72 fol=true srch=true q=\"ms<\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x3d": "off=72 fol=true srch=true q=\"ms=\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x3e": "off=72 fol=true srch=true q=\"ms>\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x3f": "off=72 fol=true srch=true q=\"ms?\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x40": "off=72 fol=true srch=true q=\"ms@\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x41": "off=72 fol=true srch=true q=\"msA\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x42": "off=72 fol=true srch=true q=\"msB\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x43": "off=72 fol=true srch=true q=\"msC\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x44": "off=72 fol=true srch=true q=\"msD\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x45": "off=72 fol=true srch=true q=\"msE\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x46": "off=72 fol=true srch=true q=\"msF\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x47": "off=72 fol=true srch=true q=\"msG\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x48": "off=72 fol=true srch=true q=\"msH\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x49": "off=72 fol=true srch=true q=\"msI\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x4a": "off=72 fol=true srch=true q=\"msJ\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x4b": "off=72 fol=true srch=true q=\"msK\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x4c": "off=72 fol=true srch=true q=\"msL\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x4d": "off=72 fol=true srch=true q=\"msM\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x4e": "off=72 fol=true srch=true q=\"msN\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x4f": "off=72 fol=true srch=true q=\"msO\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x50": "off=72 fol=true srch=true q=\"msP\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x51": "off=72 fol=true srch=true q=\"msQ\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x52": "off=72 fol=true srch=true q=\"msR\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x53": "off=72 fol=true srch=true q=\"msS\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x54": "off=72 fol=true srch=true q=\"msT\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x55": "off=72 fol=true srch=true q=\"msU\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x56": "off=72 fol=true srch=true q=\"msV\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x57": "off=72 fol=true srch=true q=\"msW\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x58": "off=72 fol=true srch=true q=\"msX\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x59": "off=72 fol=true srch=true q=\"msY\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x5a": "off=72 fol=true srch=true q=\"msZ\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x5b": "off=72 fol=true srch=true q=\"ms[\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x5c": "off=72 fol=true srch=true q=\"ms\\\\\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x5d": "off=72 fol=true srch=true q=\"ms]\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x5e": "off=72 fol=true srch=true q=\"ms^\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x5f": "off=72 fol=true srch=true q=\"ms_\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x60": "off=72 fol=true srch=true q=\"ms`\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x61": "off=72 fol=true srch=true q=\"msa\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x62": "off=72 fol=true srch=true q=\"msb\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x63": "off=72 fol=true srch=true q=\"msc\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x64": "off=72 fol=true srch=true q=\"msd\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x65": "off=72 fol=true srch=true q=\"mse\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x66": "off=72 fol=true srch=true q=\"msf\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x67": "off=72 fol=true srch=true q=\"msg\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x68": "off=72 fol=true srch=true q=\"msh\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x69": "off=72 fol=true srch=true q=\"msi\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x6a": "off=72 fol=true srch=true q=\"msj\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x6b": "off=72 fol=true srch=true q=\"msk\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x6c": "off=72 fol=true srch=true q=\"msl\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x6d": "off=72 fol=true srch=true q=\"msm\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x6e": "off=72 fol=true srch=true q=\"msn\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x6f": "off=72 fol=true srch=true q=\"mso\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x70": "off=72 fol=true srch=true q=\"msp\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x71": "off=72 fol=true srch=true q=\"msq\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x72": "off=72 fol=true srch=true q=\"msr\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x73": "off=72 fol=true srch=true q=\"mss\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x74": "off=72 fol=true srch=true q=\"mst\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x75": "off=72 fol=true srch=true q=\"msu\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x76": "off=72 fol=true srch=true q=\"msv\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x77": "off=72 fol=true srch=true q=\"msw\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x78": "off=72 fol=true srch=true q=\"msx\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x79": "off=72 fol=true srch=true q=\"msy\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x7a": "off=72 fol=true srch=true q=\"msz\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x7b": "off=72 fol=true srch=true q=\"ms{\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x7c": "off=72 fol=true srch=true q=\"ms|\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x7d": "off=72 fol=true srch=true q=\"ms}\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x7e": "off=72 fol=true srch=true q=\"ms~\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
		"0x7f": "off=72 fol=true srch=true q=\"m\" mq=\"\" h=false s=false Q=false g=false sel=false old=false new=false exp=0",
	}},
	{"search+sel", "off=2 fol=false srch=true q=\"m\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0", map[string]string{
		"0x08": "off=2 fol=false srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x0a": "off=3 fol=false srch=false q=\"m\" mq=\"m\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x0d": "off=3 fol=false srch=false q=\"m\" mq=\"m\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x1b": "off=2 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x20": "off=2 fol=false srch=true q=\"m \" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x21": "off=2 fol=false srch=true q=\"m!\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x22": "off=2 fol=false srch=true q=\"m\\\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x23": "off=2 fol=false srch=true q=\"m#\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x24": "off=2 fol=false srch=true q=\"m$\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x25": "off=2 fol=false srch=true q=\"m%\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x26": "off=2 fol=false srch=true q=\"m&\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x27": "off=2 fol=false srch=true q=\"m'\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x28": "off=2 fol=false srch=true q=\"m(\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x29": "off=2 fol=false srch=true q=\"m)\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x2a": "off=2 fol=false srch=true q=\"m*\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x2b": "off=2 fol=false srch=true q=\"m+\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x2c": "off=2 fol=false srch=true q=\"m,\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x2d": "off=2 fol=false srch=true q=\"m-\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x2e": "off=2 fol=false srch=true q=\"m.\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x2f": "off=2 fol=false srch=true q=\"m/\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x30": "off=2 fol=false srch=true q=\"m0\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x31": "off=2 fol=false srch=true q=\"m1\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x32": "off=2 fol=false srch=true q=\"m2\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x33": "off=2 fol=false srch=true q=\"m3\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x34": "off=2 fol=false srch=true q=\"m4\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x35": "off=2 fol=false srch=true q=\"m5\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x36": "off=2 fol=false srch=true q=\"m6\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x37": "off=2 fol=false srch=true q=\"m7\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x38": "off=2 fol=false srch=true q=\"m8\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x39": "off=2 fol=false srch=true q=\"m9\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x3a": "off=2 fol=false srch=true q=\"m:\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x3b": "off=2 fol=false srch=true q=\"m;\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x3c": "off=2 fol=false srch=true q=\"m<\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x3d": "off=2 fol=false srch=true q=\"m=\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x3e": "off=2 fol=false srch=true q=\"m>\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x3f": "off=2 fol=false srch=true q=\"m?\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x40": "off=2 fol=false srch=true q=\"m@\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x41": "off=2 fol=false srch=true q=\"mA\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x42": "off=2 fol=false srch=true q=\"mB\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x43": "off=2 fol=false srch=true q=\"mC\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x44": "off=2 fol=false srch=true q=\"mD\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x45": "off=2 fol=false srch=true q=\"mE\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x46": "off=2 fol=false srch=true q=\"mF\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x47": "off=2 fol=false srch=true q=\"mG\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x48": "off=2 fol=false srch=true q=\"mH\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x49": "off=2 fol=false srch=true q=\"mI\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x4a": "off=2 fol=false srch=true q=\"mJ\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x4b": "off=2 fol=false srch=true q=\"mK\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x4c": "off=2 fol=false srch=true q=\"mL\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x4d": "off=2 fol=false srch=true q=\"mM\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x4e": "off=2 fol=false srch=true q=\"mN\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x4f": "off=2 fol=false srch=true q=\"mO\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x50": "off=2 fol=false srch=true q=\"mP\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x51": "off=2 fol=false srch=true q=\"mQ\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x52": "off=2 fol=false srch=true q=\"mR\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x53": "off=2 fol=false srch=true q=\"mS\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x54": "off=2 fol=false srch=true q=\"mT\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x55": "off=2 fol=false srch=true q=\"mU\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x56": "off=2 fol=false srch=true q=\"mV\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x57": "off=2 fol=false srch=true q=\"mW\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x58": "off=2 fol=false srch=true q=\"mX\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x59": "off=2 fol=false srch=true q=\"mY\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x5a": "off=2 fol=false srch=true q=\"mZ\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x5b": "off=2 fol=false srch=true q=\"m[\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x5c": "off=2 fol=false srch=true q=\"m\\\\\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x5d": "off=2 fol=false srch=true q=\"m]\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x5e": "off=2 fol=false srch=true q=\"m^\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x5f": "off=2 fol=false srch=true q=\"m_\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x60": "off=2 fol=false srch=true q=\"m`\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x61": "off=2 fol=false srch=true q=\"ma\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x62": "off=2 fol=false srch=true q=\"mb\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x63": "off=2 fol=false srch=true q=\"mc\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x64": "off=2 fol=false srch=true q=\"md\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x65": "off=2 fol=false srch=true q=\"me\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x66": "off=2 fol=false srch=true q=\"mf\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x67": "off=2 fol=false srch=true q=\"mg\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x68": "off=2 fol=false srch=true q=\"mh\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x69": "off=2 fol=false srch=true q=\"mi\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x6a": "off=2 fol=false srch=true q=\"mj\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x6b": "off=2 fol=false srch=true q=\"mk\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x6c": "off=2 fol=false srch=true q=\"ml\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x6d": "off=2 fol=false srch=true q=\"mm\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x6e": "off=2 fol=false srch=true q=\"mn\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x6f": "off=2 fol=false srch=true q=\"mo\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x70": "off=2 fol=false srch=true q=\"mp\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x71": "off=2 fol=false srch=true q=\"mq\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x72": "off=2 fol=false srch=true q=\"mr\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x73": "off=2 fol=false srch=true q=\"ms\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x74": "off=2 fol=false srch=true q=\"mt\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x75": "off=2 fol=false srch=true q=\"mu\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x76": "off=2 fol=false srch=true q=\"mv\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x77": "off=2 fol=false srch=true q=\"mw\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x78": "off=2 fol=false srch=true q=\"mx\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x79": "off=2 fol=false srch=true q=\"my\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x7a": "off=2 fol=false srch=true q=\"mz\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x7b": "off=2 fol=false srch=true q=\"m{\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x7c": "off=2 fol=false srch=true q=\"m|\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x7d": "off=2 fol=false srch=true q=\"m}\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x7e": "off=2 fol=false srch=true q=\"m~\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
		"0x7f": "off=2 fol=false srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true old=false new=false exp=0",
	}},
}

// TestKeymap_PagerBehaviourIsUnchanged sweeps every byte and every navigation
// key through every mode and compares against the frozen oracle.
func TestKeymap_PagerBehaviourIsUnchanged(t *testing.T) {
	for _, row := range pagerOracle {
		setup, ok := oracleStates[row.state]
		if !ok {
			t.Fatalf("oracle names state %q, which the harness does not build", row.state)
		}
		t.Run(row.state, func(t *testing.T) {
			press := func(name string, press func(*transcript)) {
				tr := oracleTranscript()
				setup(tr)
				press(tr)
				want, special := row.keys[name]
				if !special {
					want = row.inert
				}
				if got := oracleSignature(tr); got != want {
					verdict := "differs from the pre-refactor dispatch"
					if !special {
						verdict = "was inert before the refactor and is not now"
					}
					t.Errorf("%s in %s mode %s:\n got %s\nwant %s", name, row.state, verdict, got, want)
				}
			}
			for b := 0; b < 128; b++ {
				b := byte(b)
				press(fmt.Sprintf("0x%02x", b), func(tr *transcript) { tr.key(b) })
			}
			for n := navUp; n <= navEnd; n++ {
				n := n
				press(navName(n), func(tr *transcript) { tr.navMotion(n) })
			}
		})
	}
}

// TestKeymap_OracleCoversEveryPagerRow: the sweep above is only as good as its
// states. Every pager-level binding must be exercised by at least one row of
// the oracle — otherwise a binding could be silently broken.
func TestKeymap_OracleCoversEveryPagerRow(t *testing.T) {
	covered := map[keyMode]bool{}
	for _, row := range pagerOracle {
		tr := oracleTranscript()
		oracleStates[row.state](tr)
		covered[tr.mode()] = true
	}
	for i := range keymap {
		bd := &keymap[i]
		if bd.pager == nil {
			continue
		}
		for m := keyMode(0); m < numKeyModes; m++ {
			if bd.modes&(1<<m) == 0 || covered[m] {
				continue
			}
			t.Errorf("%s is live in %s mode, which the equivalence oracle never starts in",
				bd.chord, modeName(m))
		}
	}
}
