package cli

import (
	"fmt"
	"testing"
	"time"

	"github.com/jack-work/figaro/api/livedoc"
	"github.com/jack-work/figaro/internal/livelog/aria"
	ldrender "github.com/jack-work/figaro/internal/livelog/render"
)

// ---------------------------------------------------------------------------
// Behavioural equivalence: the keymap must do exactly what the five inline
// switches did.
//
// The table below was GENERATED by running the pre-refactor code (45bee38,
// "docs(cli): the help panel and ui-stream list the arrow cluster") over every
// key in every pager mode and recording the resulting state. It is a frozen
// oracle, not an aspiration: the refactor is correct exactly insofar as it
// reproduces this, and any future change to a binding has to change a line
// here on purpose.
//
// Each row is a starting state: the signature an INERT key leaves (an unbound
// control byte), plus every key that leaves something else. So a key missing
// from the map is an assertion too: it must be a no-op in that mode.
//
// The off= column was rebased once, by sepRows: the separator between two
// messages lost its trailing blank (transcript_index.go), so this fixture's
// seven message boundaries are one row shorter each and every off= fell by 7.
// A re-measurement, not a behaviour change: fol=, the selection identity and
// every other column are byte-identical to 45bee38. See the longer note in
// keymap_input_equiv_test.go for the one fixture where the shrink made the
// line space GROW instead.
// ---------------------------------------------------------------------------

// oracleTranscript is the fixture the oracle was recorded against: eight
// two-node messages in a 50x8 pane, entered (and so following the tail).
func oracleTranscript() *transcript {
	ft := ldrender.NewFakeTerminal(50, 8)
	client := aria.NewClient()
	for i := 1; i <= 8; i++ {
		client.Apply(aria.Page{Parts: []aria.TurnPart{{Turn: aria.Turn{
			ID: uint64(i), Sealed: true,
			Nodes: []livedoc.Node{
				{Type: livedoc.NodeProse, Markdown: fmt.Sprintf("msg%02d body", i)},
				{Type: livedoc.NodeTool, Name: "bash", Output: fmt.Sprintf("out%02d", i)},
			},
		}}}})
	}
	tr := newTranscript(ft, 50, 8, ldrender.NodeText{}, client, "aria1234", time.Unix(0, 0))
	tr.enter()
	return tr
}

// offToken reports what a key did to the SCROLL POSITION, relative to where an
// inert key in the same state leaves it.
//
// It is relative because the absolute offset is not what this oracle is for.
// Following the tail pins the offset at `total_lines - body`, so any change to
// how a message is drawn moves every recorded number while changing no
// binding at all, which has now happened often enough to be the main cost of
// owning the table. A delta is a statement about the KEY ("u scrolls a page
// up"), and a page is a function of the pane, not of the conversation.
//
// `top` is absolute on purpose: Home goes to line 0 whatever the content, and
// recording that as a delta would put the content length back in the table.
func offToken(tr *transcript, base int) string {
	_, maxOff := tr.layout(len(tr.footLines()))
	off := tr.offset
	switch {
	case off == base:
		return "off:same"
	case off == 0:
		return "off:top"
	case tr.follow && off == maxOff:
		// FOLLOWING: the offset is not a position the key chose, it is a
		// consequence of being pinned to the tail, entering the transcript,
		// toggling verbose and opening a panel all re-pin it. Recorded by name
		// so the number, which is content length, stays out of the table.
		//
		// Not following is the other case: there the offset IS a position, and
		// the delta is the assertion worth keeping.
		return "off:bottom"
	case tr.selection.active:
		// SELECTION-DRIVEN: the offset is wherever the selected node had to be
		// scrolled to, so it is a fact about the node's position in the
		// conversation, not about the key. `sel=true` next door already says
		// the key selected something; the distance it travelled is content.
		return "off:sel"
	}
	return fmt.Sprintf("off:%+d", off-base)
}

// oracleSignature is every piece of pager state a keystroke can touch. base is
// the offset an inert key leaves in this state; see offToken.
func oracleSignature(tr *transcript, base int) string {
	return fmt.Sprintf("%s fol=%v srch=%v q=%q mq=%q h=%v s=%v Q=%v g=%v sel=%v exp=%d jmp=%v jq=%q",
		offToken(tr, base), tr.follow, tr.inSearch, tr.query, tr.matchQuery,
		tr.showing("help"), tr.showing("status"), tr.showing("queue"), tr.pendG, tr.selection.active,
		len(tr.expanded), tr.inJump, tr.cmdline.String())
}

// inertOffset is where the offset sits after a key this state does not bind,
// the reference every cell in the row is measured against. The probe key is
// chosen from the row itself, so a state that later binds 0x01 cannot silently
// start measuring against something that moves.
func inertOffset(setup func(*transcript), bound map[string]string) int {
	probe := byte(0)
	for b := 0; b < 128; b++ {
		if _, taken := bound[fmt.Sprintf("0x%02x", b)]; !taken {
			probe = byte(b)
			break
		}
	}
	tr := oracleTranscript()
	setup(tr)
	tr.key(probe)
	return tr.offset
}

// The starting states, by the name the oracle records them under.
var oracleStates = map[string]func(*transcript){
	"transcript":       func(tr *transcript) {},
	"transcript+sel":   func(tr *transcript) { tr.selectNode(1, false); tr.render() },
	"transcript+pendG": func(tr *transcript) { tr.key('g') },
	"help":             func(tr *transcript) { tr.key('?') },
	"status":           func(tr *transcript) { tr.key('!') },
	"queued":           func(tr *transcript) { tr.key('Q') },
	"panel+sel":        func(tr *transcript) { tr.selectNode(1, false); tr.key('!') },
	"search":           func(tr *transcript) { tr.key('/'); tr.key('m'); tr.key('s') },
	"search+sel":       func(tr *transcript) { tr.selectNode(1, false); tr.key('/'); tr.key('m') },
	"jump":             func(tr *transcript) { tr.key(':'); tr.key('1'); tr.key('2') },
}

// REBASED A SECOND TIME, for the cold-selection seed (Ctrl-N/Ctrl-P). Two
// causes have moved this oracle in quick succession and they must not be
// confused:
//
//   - sepRows (c1ef47f) shrank the separator by one row, so every off= fell by
//     a CONSTANT one-per-message-boundary. fol= did not move; which block was
//     selected did not move. That regeneration is already in this file.
//   - THIS one is behavioural. A cold selection used to seed from the ends of
//     the RETAINED WINDOW (len(refs)-1 for ^P, 0 for ^N) and then let
//     ensureSelectionVisible drag the page to it. It now seeds from the
//     VIEWPORT and does not scroll. Every fixture whose state is built by a
//     cold selectNode therefore STARTS somewhere else, and every key measured
//     from it reports a different off=.
//
// Three columns other than off= moved, all in the +sel states, and both
// patterns are consequences of that new starting position rather than of the
// keys themselves:
//
//   - old= true->false on the upward scroll. The old fixture started at the top
//     of the window (off=2), so scrolling up hit the edge and armed the
//     older-history prefetch. From where the reader actually is, it does not.
//   - fol= false->true with new= true->false on the four downward scrolls.
//     From off=59 a half-page down runs past the last row, which re-attaches to
//     the tail (pagerTail), and following does not arm the newer prefetch. That
//     is the documented live-padding behaviour, reached now and not before.
//
// Regenerated a THIRD time, for the ':' coordinate jump. Two classes of
// movement, both mechanical, and the generator's output was diffed against the
// previous literal cell by cell before it was installed:
//
//   - EVERY expectation gained the suffix ` jmp=false jq=""`. The signature
//     grew two columns (the jump box's open flag and its text) because a state
//     the oracle cannot see is a state the oracle cannot certify.
//   - the `0x3a` cell in the seven states where ':' used to be INERT now
//     reports `jmp=true`. Nothing else in those cells moved: off=, fol=, sel=,
//     old=, new= and exp= are byte-identical, because opening the box is all
//     the key does. In the two SEARCH states ':' is still literal text
//     (q="ms:"), which is why they appear here with the suffix and nothing
//     else: that is the "':' is a character inside the search box" rule,
//     asserted rather than asserted-about.
//
// REBASED A FOURTH TIME, and this one is a COLUMN REMOVAL, not a behaviour
// change: `old=` and `new=` reported checkOlder/checkNewer, the two armed
// prefetch flags, and phase 2a-part-2 deleted them (whether the pager wants
// history is derived from the offset, the store and the wire: see wantOlder).
// The two columns were stripped from every literal mechanically, and NOT ONE
// other cell moved: the whole table passed unchanged on the first run, which is
// the evidence that removing the flags left the keystrokes alone.
//
// And one new state, "jump", so TestKeymap_OracleCoversEveryPagerRow can
// reach the box's own rows: which is where '/' is proved to be literal text
// in there, the mirror of the rule above.
//
// REGENERATED AGAIN for the DRAWER (drawer.go). One structural change, and it
// moved 18 cells in the pager table and 9 here: the ':' and '/' boxes used to
// write themselves into the STATUS ROW, and now they are drawers, so opening
// one costs the transcript two rows. While following, the offset therefore
// lands at the new bottom rather than staying put -- which is the same PLACE,
// described by a different token (off:bottom, not off:same).
//
// That cost is the deliberate trade: the status bar carries the mantra, the
// context percentage and the cost, and it used to disappear the moment you
// typed '/'.
//
// Regenerated mechanically, not hand-edited.
var pagerOracle = []struct {
	state string
	inert string
	keys  map[string]string
}{
	{"help", "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"", map[string]string{
		// REGENERATED for THE PICKER (picker.go): every drawer now owns the
		// list motions -- j/k, u/d, gg/G and the arrow cluster move whichever
		// drawer is open instead of wiping it and acting on the transcript
		// behind it. That was the point: the help panel is the list that tells
		// you how to scroll and it was the one list you could not scroll.
		// Panels that are a GLANCE (a message) keep the any-key-dismisses rule.
		"0x0e": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x10": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x47": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x64": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x67": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=true sel=false exp=0 jmp=false jq=\"\"",
		"0x6a": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x6b": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x75": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x79": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"Down": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"End":  "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"Home": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"PgDn": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"PgUp": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"Up":   "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x21": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x2f": "off:bottom fol=true srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x3a": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"\"",
		"0x51": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x78": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
	}},
	{"jump", "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12\"", map[string]string{
		"0x08": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"1\"",
		"0x0a": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x0d": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		// THE COMMAND LINE HAS THE EMACS BINDINGS NOW, and these are the ones
		// this oracle can see: the signature records the LINE, so ^A/^E/^B/^F
		// (cursor), ^L (repaint), ^R/^S (a search whose needle is empty) and
		// Tab/^N/^P/^Y (no completer, empty history, empty kill ring in a
		// fixture) are indistinguishable from inert here. ^U kills to the
		// start and ^W kills a word, and both empty a two-character line.
		"0x15": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"\"",
		"0x17": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"\"",
		// THE FOUR CELLS THE READLINE PASS MOVED, each because a key that used
		// to belong to the process now belongs to the line while the box is up
		// (keymap.go, `&^ inJumpBox`). Nothing outside jump mode moved: the
		// other four states in this table passed unchanged.
		//   ^C and ^G abandon the line and close the box (they used to end the
		//   session and be inert respectively) -- off:bottom because closing
		//   the drawer gives the transcript its two rows back, exactly as Esc
		//   at 0x1b already did.
		"0x03": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x07": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		//   ^T transposes the two characters of "12"; it used to re-enter a
		//   pager that was already up.
		"0x14": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"21\"",
		//   ^_ undoes the typing that put "12" there. A run of insertions is
		//   ONE undo step, which is why the line goes empty rather than to "1".
		"0x1f": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"\"",
		"0x1b": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x20": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12 \"",
		"0x21": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12!\"",
		"0x22": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12\\\"\"",
		"0x23": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12#\"",
		"0x24": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12$\"",
		"0x25": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12%\"",
		"0x26": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12&\"",
		"0x27": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12'\"",
		"0x28": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12(\"",
		"0x29": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12)\"",
		"0x2a": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12*\"",
		"0x2b": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12+\"",
		"0x2c": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12,\"",
		"0x2d": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12-\"",
		"0x2e": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12.\"",
		"0x2f": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12/\"",
		"0x30": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"120\"",
		"0x31": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"121\"",
		"0x32": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"122\"",
		"0x33": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"123\"",
		"0x34": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"124\"",
		"0x35": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"125\"",
		"0x36": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"126\"",
		"0x37": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"127\"",
		"0x38": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"128\"",
		"0x39": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"129\"",
		"0x3a": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12:\"",
		"0x3b": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12;\"",
		"0x3c": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12<\"",
		"0x3d": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12=\"",
		"0x3e": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12>\"",
		"0x3f": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12?\"",
		"0x40": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12@\"",
		"0x41": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12A\"",
		"0x42": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12B\"",
		"0x43": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12C\"",
		"0x44": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12D\"",
		"0x45": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12E\"",
		"0x46": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12F\"",
		"0x47": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12G\"",
		"0x48": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12H\"",
		"0x49": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12I\"",
		"0x4a": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12J\"",
		"0x4b": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12K\"",
		"0x4c": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12L\"",
		"0x4d": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12M\"",
		"0x4e": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12N\"",
		"0x4f": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12O\"",
		"0x50": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12P\"",
		"0x51": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12Q\"",
		"0x52": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12R\"",
		"0x53": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12S\"",
		"0x54": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12T\"",
		"0x55": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12U\"",
		"0x56": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12V\"",
		"0x57": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12W\"",
		"0x58": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12X\"",
		"0x59": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12Y\"",
		"0x5a": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12Z\"",
		"0x5b": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12[\"",
		"0x5c": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12\\\\\"",
		"0x5d": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12]\"",
		"0x5e": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12^\"",
		"0x5f": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12_\"",
		"0x60": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12`\"",
		"0x61": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12a\"",
		"0x62": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12b\"",
		"0x63": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12c\"",
		"0x64": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12d\"",
		"0x65": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12e\"",
		"0x66": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12f\"",
		"0x67": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12g\"",
		"0x68": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12h\"",
		"0x69": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12i\"",
		"0x6a": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12j\"",
		"0x6b": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12k\"",
		"0x6c": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12l\"",
		"0x6d": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12m\"",
		"0x6e": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12n\"",
		"0x6f": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12o\"",
		"0x70": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12p\"",
		"0x71": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12q\"",
		"0x72": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12r\"",
		"0x73": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12s\"",
		"0x74": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12t\"",
		"0x75": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12u\"",
		"0x76": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12v\"",
		"0x77": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12w\"",
		"0x78": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12x\"",
		"0x79": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12y\"",
		"0x7a": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12z\"",
		"0x7b": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12{\"",
		"0x7c": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12|\"",
		"0x7d": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12}\"",
		"0x7e": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"12~\"",
		"0x7f": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"1\"",
	}},
	{"panel+sel", "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"", map[string]string{
		// REGENERATED for THE PICKER (picker.go): every drawer now owns the
		// list motions -- j/k, u/d, gg/G and the arrow cluster move whichever
		// drawer is open instead of wiping it and acting on the transcript
		// behind it. That was the point: the help panel is the list that tells
		// you how to scroll and it was the one list you could not scroll.
		// Panels that are a GLANCE (a message) keep the any-key-dismisses rule.
		"0x0e": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x10": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x47": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x64": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x67": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=true sel=true exp=0 jmp=false jq=\"\"",
		"0x6a": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x6b": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x75": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x79": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"Down": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"End":  "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"Home": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"PgDn": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"PgUp": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"Up":   "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x2f": "off:same fol=false srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x3a": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=true jq=\"\"",
		"0x3f": "off:same fol=false srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x51": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x78": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
	}},
	{"queued", "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"", map[string]string{
		// REGENERATED for THE PICKER (picker.go): every drawer now owns the
		// list motions -- j/k, u/d, gg/G and the arrow cluster move whichever
		// drawer is open instead of wiping it and acting on the transcript
		// behind it. That was the point: the help panel is the list that tells
		// you how to scroll and it was the one list you could not scroll.
		// Panels that are a GLANCE (a message) keep the any-key-dismisses rule.
		"0x0e": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x10": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x47": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x64": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x67": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=true sel=false exp=0 jmp=false jq=\"\"",
		"0x6a": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x6b": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x75": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x79": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"Down": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"End":  "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"Home": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"PgDn": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"PgUp": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"Up":   "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x21": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x2f": "off:bottom fol=true srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x3a": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"\"",
		"0x3f": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x78": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
	}},
	{"search", "off:same fol=true srch=true q=\"ms\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"", map[string]string{
		"0x08": "off:same fol=true srch=true q=\"m\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x0a": "off:-50 fol=false srch=false q=\"ms\" mq=\"ms\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x0d": "off:-50 fol=false srch=false q=\"ms\" mq=\"ms\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x1b": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x20": "off:same fol=true srch=true q=\"ms \" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x21": "off:same fol=true srch=true q=\"ms!\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x22": "off:same fol=true srch=true q=\"ms\\\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x23": "off:same fol=true srch=true q=\"ms#\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x24": "off:same fol=true srch=true q=\"ms$\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x25": "off:same fol=true srch=true q=\"ms%\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x26": "off:same fol=true srch=true q=\"ms&\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x27": "off:same fol=true srch=true q=\"ms'\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x28": "off:same fol=true srch=true q=\"ms(\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x29": "off:same fol=true srch=true q=\"ms)\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x2a": "off:same fol=true srch=true q=\"ms*\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x2b": "off:same fol=true srch=true q=\"ms+\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x2c": "off:same fol=true srch=true q=\"ms,\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x2d": "off:same fol=true srch=true q=\"ms-\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x2e": "off:same fol=true srch=true q=\"ms.\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x2f": "off:same fol=true srch=true q=\"ms/\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x30": "off:same fol=true srch=true q=\"ms0\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x31": "off:same fol=true srch=true q=\"ms1\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x32": "off:same fol=true srch=true q=\"ms2\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x33": "off:same fol=true srch=true q=\"ms3\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x34": "off:same fol=true srch=true q=\"ms4\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x35": "off:same fol=true srch=true q=\"ms5\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x36": "off:same fol=true srch=true q=\"ms6\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x37": "off:same fol=true srch=true q=\"ms7\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x38": "off:same fol=true srch=true q=\"ms8\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x39": "off:same fol=true srch=true q=\"ms9\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x3a": "off:same fol=true srch=true q=\"ms:\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x3b": "off:same fol=true srch=true q=\"ms;\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x3c": "off:same fol=true srch=true q=\"ms<\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x3d": "off:same fol=true srch=true q=\"ms=\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x3e": "off:same fol=true srch=true q=\"ms>\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x3f": "off:same fol=true srch=true q=\"ms?\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x40": "off:same fol=true srch=true q=\"ms@\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x41": "off:same fol=true srch=true q=\"msA\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x42": "off:same fol=true srch=true q=\"msB\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x43": "off:same fol=true srch=true q=\"msC\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x44": "off:same fol=true srch=true q=\"msD\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x45": "off:same fol=true srch=true q=\"msE\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x46": "off:same fol=true srch=true q=\"msF\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x47": "off:same fol=true srch=true q=\"msG\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x48": "off:same fol=true srch=true q=\"msH\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x49": "off:same fol=true srch=true q=\"msI\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x4a": "off:same fol=true srch=true q=\"msJ\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x4b": "off:same fol=true srch=true q=\"msK\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x4c": "off:same fol=true srch=true q=\"msL\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x4d": "off:same fol=true srch=true q=\"msM\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x4e": "off:same fol=true srch=true q=\"msN\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x4f": "off:same fol=true srch=true q=\"msO\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x50": "off:same fol=true srch=true q=\"msP\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x51": "off:same fol=true srch=true q=\"msQ\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x52": "off:same fol=true srch=true q=\"msR\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x53": "off:same fol=true srch=true q=\"msS\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x54": "off:same fol=true srch=true q=\"msT\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x55": "off:same fol=true srch=true q=\"msU\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x56": "off:same fol=true srch=true q=\"msV\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x57": "off:same fol=true srch=true q=\"msW\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x58": "off:same fol=true srch=true q=\"msX\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x59": "off:same fol=true srch=true q=\"msY\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x5a": "off:same fol=true srch=true q=\"msZ\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x5b": "off:same fol=true srch=true q=\"ms[\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x5c": "off:same fol=true srch=true q=\"ms\\\\\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x5d": "off:same fol=true srch=true q=\"ms]\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x5e": "off:same fol=true srch=true q=\"ms^\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x5f": "off:same fol=true srch=true q=\"ms_\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x60": "off:same fol=true srch=true q=\"ms`\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x61": "off:same fol=true srch=true q=\"msa\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x62": "off:same fol=true srch=true q=\"msb\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x63": "off:same fol=true srch=true q=\"msc\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x64": "off:same fol=true srch=true q=\"msd\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x65": "off:same fol=true srch=true q=\"mse\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x66": "off:same fol=true srch=true q=\"msf\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x67": "off:same fol=true srch=true q=\"msg\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x68": "off:same fol=true srch=true q=\"msh\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x69": "off:same fol=true srch=true q=\"msi\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x6a": "off:same fol=true srch=true q=\"msj\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x6b": "off:same fol=true srch=true q=\"msk\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x6c": "off:same fol=true srch=true q=\"msl\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x6d": "off:same fol=true srch=true q=\"msm\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x6e": "off:same fol=true srch=true q=\"msn\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x6f": "off:same fol=true srch=true q=\"mso\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x70": "off:same fol=true srch=true q=\"msp\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x71": "off:same fol=true srch=true q=\"msq\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x72": "off:same fol=true srch=true q=\"msr\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x73": "off:same fol=true srch=true q=\"mss\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x74": "off:same fol=true srch=true q=\"mst\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x75": "off:same fol=true srch=true q=\"msu\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x76": "off:same fol=true srch=true q=\"msv\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x77": "off:same fol=true srch=true q=\"msw\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x78": "off:same fol=true srch=true q=\"msx\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x79": "off:same fol=true srch=true q=\"msy\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x7a": "off:same fol=true srch=true q=\"msz\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x7b": "off:same fol=true srch=true q=\"ms{\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x7c": "off:same fol=true srch=true q=\"ms|\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x7d": "off:same fol=true srch=true q=\"ms}\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x7e": "off:same fol=true srch=true q=\"ms~\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x7f": "off:same fol=true srch=true q=\"m\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
	}},
	{"search+sel", "off:same fol=false srch=true q=\"m\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"", map[string]string{
		"0x08": "off:same fol=false srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x0a": "off:same fol=false srch=false q=\"m\" mq=\"m\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x0d": "off:same fol=false srch=false q=\"m\" mq=\"m\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x1b": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x20": "off:same fol=false srch=true q=\"m \" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x21": "off:same fol=false srch=true q=\"m!\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x22": "off:same fol=false srch=true q=\"m\\\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x23": "off:same fol=false srch=true q=\"m#\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x24": "off:same fol=false srch=true q=\"m$\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x25": "off:same fol=false srch=true q=\"m%\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x26": "off:same fol=false srch=true q=\"m&\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x27": "off:same fol=false srch=true q=\"m'\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x28": "off:same fol=false srch=true q=\"m(\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x29": "off:same fol=false srch=true q=\"m)\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x2a": "off:same fol=false srch=true q=\"m*\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x2b": "off:same fol=false srch=true q=\"m+\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x2c": "off:same fol=false srch=true q=\"m,\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x2d": "off:same fol=false srch=true q=\"m-\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x2e": "off:same fol=false srch=true q=\"m.\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x2f": "off:same fol=false srch=true q=\"m/\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x30": "off:same fol=false srch=true q=\"m0\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x31": "off:same fol=false srch=true q=\"m1\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x32": "off:same fol=false srch=true q=\"m2\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x33": "off:same fol=false srch=true q=\"m3\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x34": "off:same fol=false srch=true q=\"m4\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x35": "off:same fol=false srch=true q=\"m5\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x36": "off:same fol=false srch=true q=\"m6\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x37": "off:same fol=false srch=true q=\"m7\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x38": "off:same fol=false srch=true q=\"m8\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x39": "off:same fol=false srch=true q=\"m9\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x3a": "off:same fol=false srch=true q=\"m:\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x3b": "off:same fol=false srch=true q=\"m;\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x3c": "off:same fol=false srch=true q=\"m<\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x3d": "off:same fol=false srch=true q=\"m=\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x3e": "off:same fol=false srch=true q=\"m>\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x3f": "off:same fol=false srch=true q=\"m?\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x40": "off:same fol=false srch=true q=\"m@\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x41": "off:same fol=false srch=true q=\"mA\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x42": "off:same fol=false srch=true q=\"mB\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x43": "off:same fol=false srch=true q=\"mC\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x44": "off:same fol=false srch=true q=\"mD\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x45": "off:same fol=false srch=true q=\"mE\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x46": "off:same fol=false srch=true q=\"mF\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x47": "off:same fol=false srch=true q=\"mG\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x48": "off:same fol=false srch=true q=\"mH\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x49": "off:same fol=false srch=true q=\"mI\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x4a": "off:same fol=false srch=true q=\"mJ\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x4b": "off:same fol=false srch=true q=\"mK\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x4c": "off:same fol=false srch=true q=\"mL\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x4d": "off:same fol=false srch=true q=\"mM\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x4e": "off:same fol=false srch=true q=\"mN\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x4f": "off:same fol=false srch=true q=\"mO\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x50": "off:same fol=false srch=true q=\"mP\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x51": "off:same fol=false srch=true q=\"mQ\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x52": "off:same fol=false srch=true q=\"mR\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x53": "off:same fol=false srch=true q=\"mS\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x54": "off:same fol=false srch=true q=\"mT\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x55": "off:same fol=false srch=true q=\"mU\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x56": "off:same fol=false srch=true q=\"mV\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x57": "off:same fol=false srch=true q=\"mW\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x58": "off:same fol=false srch=true q=\"mX\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x59": "off:same fol=false srch=true q=\"mY\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x5a": "off:same fol=false srch=true q=\"mZ\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x5b": "off:same fol=false srch=true q=\"m[\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x5c": "off:same fol=false srch=true q=\"m\\\\\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x5d": "off:same fol=false srch=true q=\"m]\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x5e": "off:same fol=false srch=true q=\"m^\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x5f": "off:same fol=false srch=true q=\"m_\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x60": "off:same fol=false srch=true q=\"m`\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x61": "off:same fol=false srch=true q=\"ma\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x62": "off:same fol=false srch=true q=\"mb\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x63": "off:same fol=false srch=true q=\"mc\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x64": "off:same fol=false srch=true q=\"md\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x65": "off:same fol=false srch=true q=\"me\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x66": "off:same fol=false srch=true q=\"mf\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x67": "off:same fol=false srch=true q=\"mg\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x68": "off:same fol=false srch=true q=\"mh\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x69": "off:same fol=false srch=true q=\"mi\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x6a": "off:same fol=false srch=true q=\"mj\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x6b": "off:same fol=false srch=true q=\"mk\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x6c": "off:same fol=false srch=true q=\"ml\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x6d": "off:same fol=false srch=true q=\"mm\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x6e": "off:same fol=false srch=true q=\"mn\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x6f": "off:same fol=false srch=true q=\"mo\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x70": "off:same fol=false srch=true q=\"mp\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x71": "off:same fol=false srch=true q=\"mq\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x72": "off:same fol=false srch=true q=\"mr\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x73": "off:same fol=false srch=true q=\"ms\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x74": "off:same fol=false srch=true q=\"mt\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x75": "off:same fol=false srch=true q=\"mu\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x76": "off:same fol=false srch=true q=\"mv\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x77": "off:same fol=false srch=true q=\"mw\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x78": "off:same fol=false srch=true q=\"mx\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x79": "off:same fol=false srch=true q=\"my\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x7a": "off:same fol=false srch=true q=\"mz\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x7b": "off:same fol=false srch=true q=\"m{\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x7c": "off:same fol=false srch=true q=\"m|\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x7d": "off:same fol=false srch=true q=\"m}\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x7e": "off:same fol=false srch=true q=\"m~\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x7f": "off:same fol=false srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
	}},
	{"status", "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"", map[string]string{
		// REGENERATED for THE PICKER (picker.go): every drawer now owns the
		// list motions -- j/k, u/d, gg/G and the arrow cluster move whichever
		// drawer is open instead of wiping it and acting on the transcript
		// behind it. That was the point: the help panel is the list that tells
		// you how to scroll and it was the one list you could not scroll.
		// Panels that are a GLANCE (a message) keep the any-key-dismisses rule.
		"0x0e": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x10": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x47": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x64": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x67": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=true sel=false exp=0 jmp=false jq=\"\"",
		"0x6a": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x6b": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x75": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x79": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"Down": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"End":  "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"Home": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"PgDn": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"PgUp": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"Up":   "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x2f": "off:bottom fol=true srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x3a": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"\"",
		"0x3f": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x51": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x78": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
	}},
	{"transcript", "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"", map[string]string{
		"0x0e": "off:sel fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x10": "off:sel fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x21": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x2f": "off:bottom fol=true srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x3a": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"\"",
		"0x3f": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x51": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x67": "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=true sel=false exp=0 jmp=false jq=\"\"",
		"0x6b": "off:-1 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x75": "off:-5 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"Home": "off:top fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"PgUp": "off:-5 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"Up":   "off:-1 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
	}},
	{"transcript+pendG", "off:same fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"", map[string]string{
		"0x0e": "off:sel fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x10": "off:sel fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x21": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x2f": "off:bottom fol=true srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x3a": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=true jq=\"\"",
		"0x3f": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x51": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x67": "off:top fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x6b": "off:-1 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x75": "off:-5 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"Home": "off:top fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"PgUp": "off:-5 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"Up":   "off:-1 fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
	}},
	{"transcript+sel", "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"", map[string]string{
		"0x10": "off:sel fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x1b": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=false exp=0 jmp=false jq=\"\"",
		"0x21": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=true Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x2f": "off:same fol=false srch=true q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x3a": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=true jq=\"\"",
		"0x3f": "off:same fol=false srch=false q=\"\" mq=\"\" h=true s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x47": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x51": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=true g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x64": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x67": "off:same fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=true sel=true exp=0 jmp=false jq=\"\"",
		"0x6a": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x6b": "off:sel fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"0x75": "off:sel fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"Down": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"End":  "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"Home": "off:top fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"PgDn": "off:bottom fol=true srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"PgUp": "off:sel fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
		"Up":   "off:sel fol=false srch=false q=\"\" mq=\"\" h=false s=false Q=false g=false sel=true exp=0 jmp=false jq=\"\"",
	}},
}

// sweepPager presses every byte and every navigation key in one state and
// returns what each left behind, keyed by the oracle's name for it.
//
// THE VERIFIER AND THE REGENERATOR SHARE THIS ON PURPOSE. Two copies of the
// sweep can disagree about which keys are pressed or in what state, and the
// failure mode is silent: the regenerator records cells the verifier never
// reads, and the frozen table stops describing the thing under test.
func sweepPager(setup func(*transcript), keys map[string]string) (cells map[string]string, base int) {
	base = inertOffset(setup, keys)
	cells = make(map[string]string, 128+int(navEnd-navUp)+1)
	record := func(name string, press func(*transcript)) {
		tr := oracleTranscript()
		setup(tr)
		press(tr)
		cells[name] = oracleSignature(tr, base)
	}
	for b := 0; b < 128; b++ {
		b := byte(b)
		record(fmt.Sprintf("0x%02x", b), func(tr *transcript) { tr.key(b) })
	}
	for n := navUp; n <= navEnd; n++ {
		n := n
		record(navName(n), func(tr *transcript) { tr.navMotion(n) })
	}
	return cells, base
}

// TestKeymap_PagerBehaviourIsUnchanged sweeps every byte and every navigation
// key through every mode and compares against the frozen oracle.
func TestKeymap_PagerBehaviourIsUnchanged(t *testing.T) {
	for _, row := range pagerOracle {
		setup, ok := oracleStates[row.state]
		if !ok {
			t.Fatalf("oracle names state %q, which the harness does not build", row.state)
		}
		t.Run(row.state, func(t *testing.T) {
			cells, _ := sweepPager(setup, row.keys)
			for name, got := range cells {
				want, special := row.keys[name]
				if !special {
					want = row.inert
				}
				if got != want {
					verdict := "differs from the pre-refactor dispatch"
					if !special {
						verdict = "was inert before the refactor and is not now"
					}
					t.Errorf("%s in %s mode %s:\n got %s\nwant %s", name, row.state, verdict, got, want)
				}
			}
		})
	}
}

// TestKeymap_OracleCoversEveryPagerRow: the sweep above is only as good as its
// states. Every pager-level binding must be exercised by at least one row of
// the oracle: otherwise a binding could be silently broken.
func TestKeymap_OracleCoversEveryPagerRow(t *testing.T) {
	covered := map[keyMode]bool{}
	for _, row := range pagerOracle {
		tr := oracleTranscript()
		oracleStates[row.state](tr)
		covered[tr.mode()] = true
	}
	for i := range keymap {
		bd := &keymap[i]
		if bd.pager == nil {
			continue
		}
		for m := keyMode(0); m < numKeyModes; m++ {
			if bd.modes&(1<<m) == 0 || covered[m] {
				continue
			}
			t.Errorf("%s is live in %s mode, which the equivalence oracle never starts in",
				bd.chord, modeName(m))
		}
	}
}
